---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-kubemodelrepo
  annotations:
    meta.crossplane.io/maintainer: Ivan Josipovic
    meta.crossplane.io/source: https://github.com/IvanJosipovic/function-kubemodelrepo
    meta.crossplane.io/description: |
      Crossplane Function which deploys configured GitHub Repos
    meta.crossplane.io/readme: |
      See https://github.com/IvanJosipovic/function-kubemodelrepo/blob/main/README.md for
      customizing this function.
spec:
  capabilities:
    - composition
  crossplane:
    version: ">=v2.0.0-0"
  dependsOn:
    - apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: ghcr.io/ivanjosipovic/function-kubemodelrepo/function-kubemodelrepo
      version: ">=1.0.0"
